### ISSUE TITLE
Error when running locally

### ISSUE THREAD

**Issue by doug2525** [jcustenborder/kafka-connect-salesforce#24]
When I run the development command:
~/confluent/bin/connect-standalone ~/confluent/etc/schema-registry/connect-avro-standalone.properties config/salesforce.properties

 I am getting this error. I'm sure it is something I am doing wrong but any help would be appreciated.

[2017-07-21 13:21:37,528] WARN could not get type for name com.github.jcustenborder.kafka.connect.salesforce.SalesforceSourceConnector from any class loader (org.reflections.Reflections:384)
org.reflections.ReflectionsException: could not get type for name com.github.jcustenborder.kafka.connect.salesforce.SalesforceSourceConnector
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:378)
	at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:397)
	at org.reflections.Reflections.getSubTypesOf(Reflections.java:367)
	at org.apache.kafka.connect.runtime.AbstractHerder.connectorPlugins(AbstractHerder.java:270)
	at org.apache.kafka.connect.runtime.AbstractHerder$1.run(AbstractHerder.java:377)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.github.jcustenborder.kafka.connect.salesforce.SalesforceSourceConnector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:376)
	... 5 more

**Comment by jcustenborder** [comment]
@doug2525 This looks like the Connector is not in the class path. Where are you installing it?

**Comment by doug2525** [comment]
@jcustenborder for running locally I just have it in my home folder. Then I just ran the steps under building and development. Is there an additional step I am missing?

**Comment by satishsg** [comment]
hi @jcustenborder,
I am trying to use this connector and have the same issue as @doug2525.
@doug2525 did you find a solution?

[2017-08-25 16:35:09,560] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:99)
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at com.github.jcustenborder.kafka.connect.utils.config.ValidPattern.ensureValid(ValidPattern.java:44)
	at org.apache.kafka.common.config.ConfigDef$ConfigKey.<init>(ConfigDef.java:904)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:127)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:147)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:186)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:348)
	at com.github.jcustenborder.kafka.connect.salesforce.SalesforceSourceConnectorConfig.conf(SalesforceSourceConnectorConfig.java:113)
	at com.github.jcustenborder.kafka.connect.salesforce.SalesforceSourceConnector.config(SalesforceSourceConnector.java:154)
	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:133)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:254)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:158)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:93)
[2017-08-25 16:35:09,561] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:66)

**Comment by doug2525** [comment]
@satishsg No I was never able to get the connector to work.

**Comment by jcustenborder** [comment]
@doug2525 @satishsg. Sorry I just saw this. What version of kafka connect are you using?

**Comment by satishsg** [comment]
Hi @jcustenborder @doug2525 
thanks for responding. I am not sure how to find the kafka connect version. I am running confluent 3.2.1 though. FYI, I am able to successfully use the built in jdbc connector and also the cassandra sink from http://docs.datamountaineer.com/en/latest/cassandra-sink.html.

**Comment by doug2525** [comment]
@jcustenborder not sure the exact version I was using but I tried the latest confluent stack that was available in July.

**Comment by satishsg** [comment]
@jcustenborder any thoughts on this error?

**Comment by jcustenborder** [comment]
@doug2525 @satishsg Sorry about the late response. I have trouble noticing github notifications sometimes. Have you tried with the latest version? There were changes to guava between 0.10.x and 0.11.x. What version are you running?
